import { InMemoryDbService } from 'angular2-in-memory-web-api';
export class InMemoryDataService implements InMemoryDbService {
    createDb() {
        const pellmell = [
            
            {	nom	:	"	Le tour du monde en 80 jours	"	,	nombre	:	"	1566	"	}	,
            {	nom	:	"	Amiens	"	,	nombre	:	"	954	"	}	,
            {	nom	:	"	Nantes	"	,	nombre	:	"	753	"	}	,
            {	nom	:	"	Vingt mille lieues sous les mers	"	,	nombre	:	"	747	"	}	,
            {	nom	:	"	 Le tour du monde en 80 jours	"	,	nombre	:	"	701	"	}	,
            {	nom	:	"	 Nautilus	"	,	nombre	:	"	683	"	}	,
            {	nom	:	"	 Phileas Fogg	"	,	nombre	:	"	644	"	}	,
            {	nom	:	"	Voyage au centre de la Terre	"	,	nombre	:	"	541	"	}	,
            {	nom	:	"	 Nantes	"	,	nombre	:	"	524	"	}	,
            {	nom	:	"	 Le tour du monde en 80 jours	"	,	nombre	:	"	467	"	}	,
            {	nom	:	"	20 000 lieues sous les mers	"	,	nombre	:	"	443	"	}	,
            {	nom	:	"	 Passepartout	"	,	nombre	:	"	379	"	}	,
            {	nom	:	"	 Nantes	"	,	nombre	:	"	369	"	}	,
            {	nom	:	"	 Amiens	"	,	nombre	:	"	350	"	}	,
            {	nom	:	"	 Capitaine Nemo	"	,	nombre	:	"	324	"	}	,
            {	nom	:	"	 20 000 lieues sous les mers	"	,	nombre	:	"	319	"	}	,
            {	nom	:	"	 « Le Tour du Monde en 80 jours »	"	,	nombre	:	"	312	"	}	,
            {	nom	:	"	 Voyage au centre de la Terre	"	,	nombre	:	"	311	"	}	,
            {	nom	:	"	 Théâtre	"	,	nombre	:	"	295	"	}	,
            {	nom	:	"	 Maison Jules Verne	"	,	nombre	:	"	291	"	}	,
            {	nom	:	"	 Sébastien Azzopardi	"	,	nombre	:	"	282	"	}	,
            {	nom	:	"	 SteamPunk	"	,	nombre	:	"	277	"	}	,
            {	nom	:	"	 Science-fiction	"	,	nombre	:	"	276	"	}	,
            {	nom	:	"	Paris	"	,	nombre	:	"	272	"	}	,
            {	nom	:	"	 Théâtre	"	,	nombre	:	"	269	"	}	,
            {	nom	:	"	 Nemo	"	,	nombre	:	"	261	"	}	,
            {	nom	:	"	Dani Lary	"	,	nombre	:	"	256	"	}	,
            {	nom	:	"	 De la Terre à la Lune	"	,	nombre	:	"	252	"	}	,
            {	nom	:	"	 Voyage au centre de la Terre	"	,	nombre	:	"	248	"	}	,
            {	nom	:	"	Théâtre	"	,	nombre	:	"	235	"	}	,
            {	nom	:	"	 « 20000 lieues sous les mers »	"	,	nombre	:	"	234	"	}	,
            {	nom	:	"	 Amiens	"	,	nombre	:	"	234	"	}	,
            {	nom	:	"	 Vingt mille lieues sous les mers	"	,	nombre	:	"	234	"	}	,
            {	nom	:	"	 Magie	"	,	nombre	:	"	225	"	}	,
            {	nom	:	"	 Musée Jules Verne	"	,	nombre	:	"	220	"	}	,
            {	nom	:	"	 Sous-marin	"	,	nombre	:	"	211	"	}	,
            {	nom	:	"	 Mer	"	,	nombre	:	"	203	"	}	,
            {	nom	:	"	 Vingt mille lieues sous les mers	"	,	nombre	:	"	200	"	}	,
            {	nom	:	"	 Musée Jules Verne	"	,	nombre	:	"	197	"	}	,
            {	nom	:	"	 20000 lieues sous les mers	"	,	nombre	:	"	195	"	}	,
            {	nom	:	"	Les naufragés du Fol Espoir	"	,	nombre	:	"	195	"	}	,
            {	nom	:	"	 Hetzel	"	,	nombre	:	"	190	"	}	,
            {	nom	:	"	Futuroscope	"	,	nombre	:	"	188	"	}	,
            {	nom	:	"	Science-fiction	"	,	nombre	:	"	184	"	}	,
            {	nom	:	"	 Extraordinaire voyage	"	,	nombre	:	"	183	"	}	,
            {	nom	:	"	 Nautilus	"	,	nombre	:	"	177	"	}	,
            {	nom	:	"	 Science-fiction	"	,	nombre	:	"	177	"	}	,
            {	nom	:	"	 Sydney Bernard	"	,	nombre	:	"	177	"	}	,
            {	nom	:	"	vente	"	,	nombre	:	"	177	"	}	,
            {	nom	:	"	Michel Strogoff	"	,	nombre	:	"	174	"	}	,
            {	nom	:	"	 Phileas Fogg	"	,	nombre	:	"	169	"	}	,
            {	nom	:	"	Voyages extraordinaires	"	,	nombre	:	"	168	"	}	,
            {	nom	:	"	 bateau	"	,	nombre	:	"	164	"	}	,
            {	nom	:	"	20000 lieues sous les mers	"	,	nombre	:	"	164	"	}	,
            {	nom	:	"	 Sacha Danino	"	,	nombre	:	"	163	"	}	,
            {	nom	:	"	 Révolution industrielle	"	,	nombre	:	"	161	"	}	,
            {	nom	:	"	 Parc d'attractions	"	,	nombre	:	"	160	"	}	,
            {	nom	:	"	Le tour du monde en quatre-vingts jours	"	,	nombre	:	"	155	"	}	,
            {	nom	:	"	 20 000 lieues sous les mers	"	,	nombre	:	"	145	"	}	,
            {	nom	:	"	 Cinéma	"	,	nombre	:	"	145	"	}	,
            {	nom	:	"	 Comédie musicale	"	,	nombre	:	"	145	"	}	,
            {	nom	:	"	 L'île mystérieuse	"	,	nombre	:	"	138	"	}	,
            {	nom	:	"	 Musique	"	,	nombre	:	"	138	"	}	,
            {	nom	:	"	 Voyages extraordinaires	"	,	nombre	:	"	138	"	}	,
            {	nom	:	"	 anticipation	"	,	nombre	:	"	137	"	}	,
            {	nom	:	"	Centre de loisirs	"	,	nombre	:	"	137	"	}	,
            {	nom	:	"	 Eléphant	"	,	nombre	:	"	136	"	}	,
            {	nom	:	"	 imaginaire	"	,	nombre	:	"	135	"	}	,
            {	nom	:	"	lecture	"	,	nombre	:	"	135	"	}	,
            {	nom	:	"	 la maison Jules Verne	"	,	nombre	:	"	134	"	}	,
            {	nom	:	"	BD	"	,	nombre	:	"	133	"	}	,
            {	nom	:	"	 Lyon	"	,	nombre	:	"	132	"	}	,
            {	nom	:	"	 Machines	"	,	nombre	:	"	132	"	}	,
            {	nom	:	"	 Les naufragés du Jonathan	"	,	nombre	:	"	131	"	}	,
            {	nom	:	"	 Paris	"	,	nombre	:	"	131	"	}	,
            {	nom	:	"	Sébastien Azzopardi	"	,	nombre	:	"	131	"	}	,
            {	nom	:	"	Théâtre Mogador	"	,	nombre	:	"	131	"	}	,
            {	nom	:	"	 Ariane MnouchKine	"	,	nombre	:	"	129	"	}	,
            {	nom	:	"	 Michel Strogoff	"	,	nombre	:	"	129	"	}	,
            {	nom	:	"	 Paris	"	,	nombre	:	"	129	"	}	,
            {	nom	:	"	 Steampunk	"	,	nombre	:	"	128	"	}	,
            {	nom	:	"	 Voyage	"	,	nombre	:	"	128	"	}	,
            {	nom	:	"	 Fourvière	"	,	nombre	:	"	125	"	}	,
            {	nom	:	"	Fête des lumières	"	,	nombre	:	"	125	"	}	,
            {	nom	:	"	 L'île mystérieuse	"	,	nombre	:	"	122	"	}	,
            {	nom	:	"	Cinéma	"	,	nombre	:	"	122	"	}	,
            {	nom	:	"	 Lune	"	,	nombre	:	"	121	"	}	,
            {	nom	:	"	 sous-marins	"	,	nombre	:	"	121	"	}	,
            {	nom	:	"	 invention	"	,	nombre	:	"	120	"	}	,
            {	nom	:	"	Interview Jean-Marc Ayrault	"	,	nombre	:	"	119	"	}	,
            {	nom	:	"	Musée Jules Verne	"	,	nombre	:	"	117	"	}	,
            {	nom	:	"	 Train	"	,	nombre	:	"	116	"	}	,
            {	nom	:	"	Festival	"	,	nombre	:	"	114	"	}	,
            {	nom	:	"	Voiture volante	"	,	nombre	:	"	114	"	}	,
            {	nom	:	"	 fantastique	"	,	nombre	:	"	112	"	}	,
            {	nom	:	"	 Antoine de Saint-Exupéry	"	,	nombre	:	"	111	"	}	,
            {	nom	:	"	 Stefan Klein	"	,	nombre	:	"	111	"	}	,
            {	nom	:	"	 Lecture	"	,	nombre	:	"	110	"	}	,
            {	nom	:	"	 Drouot	"	,	nombre	:	"	109	"	}	,
            {	nom	:	"	 Sébastien Azzopardi	"	,	nombre	:	"	109	"	}	,
            {	nom	:	"	L'île mystérieuse	"	,	nombre	:	"	107	"	}	,
            {	nom	:	"	Nantes (44)	"	,	nombre	:	"	107	"	}	,
            {	nom	:	"	 Cinq semaines en ballon	"	,	nombre	:	"	105	"	}	,
            {	nom	:	"	Nautilus	"	,	nombre	:	"	105	"	}	,
            {	nom	:	"	 Georges Méliès	"	,	nombre	:	"	104	"	}	,
            {	nom	:	"	 machine à vapeur	"	,	nombre	:	"	104	"	}	,
            {	nom	:	"	 Tour du monde	"	,	nombre	:	"	104	"	}	,
            {	nom	:	"	 Maison Jules Verne	"	,	nombre	:	"	102	"	}	,
            {	nom	:	"	 Voyage	"	,	nombre	:	"	102	"	}	,
            {	nom	:	"	Cinq semaines en ballon	"	,	nombre	:	"	102	"	}	,
            {	nom	:	"	 imagination	"	,	nombre	:	"	101	"	}	,
            {	nom	:	"	 Retro-temporis	"	,	nombre	:	"	101	"	}	,
            {	nom	:	"	Musique	"	,	nombre	:	"	101	"	}	,
            {	nom	:	"	Inserm	"	,	nombre	:	"	100	"	}	,
            {	nom	:	"	Montgolfière	"	,	nombre	:	"	100	"	}	,
            {	nom	:	"	 Ariane Mnouchkine	"	,	nombre	:	"	99	"	}	,
            {	nom	:	"	 Astronomie	"	,	nombre	:	"	99	"	}	,
            {	nom	:	"	 Vente aux enchères	"	,	nombre	:	"	98	"	}	,
            {	nom	:	"	 20000 lieues sous les mers	"	,	nombre	:	"	96	"	}	,
            {	nom	:	"	 David Fincher	"	,	nombre	:	"	95	"	}	,
            {	nom	:	"	 Autour de la Lune	"	,	nombre	:	"	94	"	}	,
            {	nom	:	"	 Spectacle	"	,	nombre	:	"	94	"	}	,
            {	nom	:	"	Voyage	"	,	nombre	:	"	92	"	}	,
            {	nom	:	"	 1er mars 2017	"	,	nombre	:	"	91	"	}	,
            {	nom	:	"	 Bateau	"	,	nombre	:	"	91	"	}	,
            {	nom	:	"	 Cinq semaines en ballon	"	,	nombre	:	"	91	"	}	,
            {	nom	:	"	 Profondeurs	"	,	nombre	:	"	90	"	}	,
            {	nom	:	"	 collection vernienne	"	,	nombre	:	"	89	"	}	,
            {	nom	:	"	 Slovaquie	"	,	nombre	:	"	89	"	}	,
            {	nom	:	"	 Aventure	"	,	nombre	:	"	88	"	}	,
            {	nom	:	"	 lecture	"	,	nombre	:	"	88	"	}	,
            {	nom	:	"	 mers	"	,	nombre	:	"	88	"	}	,
            {	nom	:	"	 Aéromobil	"	,	nombre	:	"	87	"	}	,
            {	nom	:	"	 Bande dessinée	"	,	nombre	:	"	87	"	}	,
            {	nom	:	"	 Disney	"	,	nombre	:	"	87	"	}	,
            {	nom	:	"	SteamPunk	"	,	nombre	:	"	87	"	}	,
            {	nom	:	"	 Tour du monde	"	,	nombre	:	"	86	"	}	,
            {	nom	:	"	 Comédie Française	"	,	nombre	:	"	85	"	}	,
            {	nom	:	"	 Michel Strogoff	"	,	nombre	:	"	85	"	}	,
            {	nom	:	"	 Sous-marin	"	,	nombre	:	"	85	"	}	,
            {	nom	:	"	De la Terre à la Lune	"	,	nombre	:	"	85	"	}	,
            {	nom	:	"	Islande	"	,	nombre	:	"	85	"	}	,
            {	nom	:	"	 Mer	"	,	nombre	:	"	84	"	}	,
            {	nom	:	"	 Livre Ancien	"	,	nombre	:	"	83	"	}	,
            {	nom	:	"	Google	"	,	nombre	:	"	83	"	}	,
            {	nom	:	"	 Musique	"	,	nombre	:	"	82	"	}	,
            {	nom	:	"	Bande dessinée	"	,	nombre	:	"	81	"	}	,
            {	nom	:	"	 Océans	"	,	nombre	:	"	80	"	}	,
            {	nom	:	"	Maison Jules Verne	"	,	nombre	:	"	79	"	}	,
            
            
        ];
        return { pellmell };
    }
}